import Link from 'next/link';
import Head from 'next/head'
import { Inter } from '@next/font/google'
import styles from '@/styles/Home.module.css'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  const name = "Aubrey"; //EDIT LATER IN SETTINGS

  return (
    <div>
      <Head>
        <title>Homepage</title>
          <meta name="description" content="Generated by create next app" />
          <meta name="viewport" content="width=device-width, initial-scale=1" />
          <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>

        <section>
          <h2>Hello, {name}</h2>
          <h1>Welcome to the Homepage!</h1>
        </section>

        <div className={styles.description}>
        <Link href="/components">Take me to Components Library</Link>
        <Link href="/settings">Take me to My Settings</Link>
        </div>

      </main>
    </div>
  )
}
